### PR TITLE
refactor: move migrate fn from util to store

### LINKED ISSUE #1: Figure out a better name for the util crate
schema? migrations?

### PR DESCRIPTION
**Pull request by mightyiam**
closes #1 (whoa)

Co-authored-by: Samyak Sarnayak <samyak201@gmail.com>

### CODE REVIEW

**Comment by mightyiam** [comment]
Didn't think this can fail.

**Comment by mightyiam** [comment]
Okay, fixed it.

**Review by jfly — COMMENTED** [review]
IIUC, this forces us to have the store compiling in order to run migrations. I think that causes an impossible circular dependency. Consider the situation where we add a new query to the store: the crate no longer compiles (because it needs an updated sqlx cache directory). In order to update the sqlx cache directory, we need to run migrations, but we can't because the store doesn't compile.

**Comment by mightyiam** [comment]
Superseded by #102

**Pull request closed without merging**
